version: '3.8'

services:

    app:
        container_name: app-hello-world
        image: app-hello-world:1.0.0
        build:
            context: .
            dockerfile: src/Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
        networks:
            - app-hello-world-network

networks:
  app-hello-world-network: